import { GraphQLSchema, isScalarType } from 'graphql';
import { sortedUniq } from 'lodash';

export const TOP_TIP = `// generated by muta-codegen, please do not edit manually
// @ts-nocheck
/* eslint-disable */
`;

const scalarMap = {
  /* null */
  Null: "Null",

  /* number */
  U32: 'U32',
  U64: 'U64',

  /* bytes like */
  Uint32: 'Uint32',
  Uint64: 'Uint64',
  Hex: 'Hex',
  Bytes: 'Bytes',
  Hash: 'Hash',
  Address: 'Address',
};

export function scalarsIn(schema: GraphQLSchema): string {
  const scalars = Object.values(schema.getTypeMap())
    .filter(field => isScalarType(field) && scalarMap[field.name])
    .map(scalar => scalar.name);

  return `import { ${sortedUniq(scalars).join(', ')} } from '@mutajs/types';`;
}
